services:
  db:
    container_name: nestjs-fundamentals-course-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
  test-db:
    container_name: nestjs-fundamentals-course-test-db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: admin
